fast: 
  boot: 
    swagger:
      title: Spring Boot中使用Swagger2构建RESTful APIs
      description: 更多Spring Boot相关文章请关注：http://blog.didispace.com/
      serviceUrl: http://blog.didispace.com/
      contact: 程序猿DD
      version: 1.0
      license: 
      licenseUrl: 