spring:
  application:
    name: config-server
  #需要从本地获取配置，请打开此配置
#  profiles:
#    active:
#    - native
  #需要从git获取配置，请打开此配置
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/sngh_lee/config-repo
          
server:
  port: 1112
  
logging:
  level:
    root: info