spring:
  application:
    name: vote-mobile
    
server:
  port: 8066
  
eureka:
  instance:
    #eureka server服务列表显示ip+port
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/
      
security:
  basic:
    enabled: false
management:
  security:
    enabled: false