spring:
  application:
    name: fast-monitor
  #设置邮件通知服务器
#  mail:
#    host: smtp.qq.com
  boot:
    admin:
      #turbine配置
      turbine:
        clusters:
        - default
        #turbine service的id
        location: fast-turbine
        #设置Notifier
#      notify:
#        mail:
#          to: 1581361@qq.com
#          subject: Service is Down
#          from: Moniter Server Admin@lish-dongfang.com

server:
  port: 8888
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/
  instance:
    #eureka server服务列表显示ip+port
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}

management:
  security:
    enabled: false
#fast monitor server配置
fast:
  boot:
    monitor:
      #开启/关闭monitor server安全登录验证
      security: true
      #开启/关闭monitor通知
      notifier: false
#关闭security默认的安全保护
security:
  basic:
    enabled: false
  #配置monitor登录用户名和密码
  user:
    name: test
    password: test