spring:
  application:
    name: fast-monitor

server:
  port: 8130
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/
  instance:
    #eureka server服务列表显示ip+port
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}

management:
  security:
    enabled: false
#配置monitor登录用户名和密码
fast:
  boot:
    monitor:
      security: true
security:
  basic:
    enabled: false
  user:
    name: test
    password: test